package main

import (
	"testing"
)

func TestSolvesPart1(t *testing.T) {
	testInput := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	result := SolvePart1(testInput)
	expected := 14

	if result != expected {
		t.Errorf("Part 1 failed. Received %d; expected %d", result, expected)
	}
}
